name: Build and Run Docker Container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t apt-s3-image .

    - name: Run Docker container
      run: |
        docker run -d --name apt-s3-container apt-s3-image

    - name: Check apt-s3 installation
      run: |
        docker exec apt-s3-container apt-s3 -help
