name: Build and Run Docker Container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create s3auth.conf from secret
      run: echo "${{ secrets.S3AUTH_CONF_CONTENT }}" > s3auth.conf

    - name: Build Docker image with BuildKit
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build --secret id=s3auth,src=s3auth.conf . -t my-docker-image

    - name: Run Docker container
      run: docker run -d --name my-container my-docker-image sleep infinity
    
    - name: Execute command inside container
      run: docker exec my-container batcat /etc/passwd
